import React from "react";
import Nav from "./Nav";
import Head from "next/head";

export default function Layout(props) {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={props.icon} />
      </Head>
      <Nav />
      <div>{props.children}</div>
    </>
  );
}
