import React from "react";
import Nav from "./Nav";
import Head from "next/head";
import Footer from "./Footer";

export default function Layout(props) {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={props.icon} />
      </Head>
      <Nav />
      <div className="relative selection:bg-red-600 selection:text-white">{props.children}</div>
      <Footer />
    </>
  );
}
